name: Containerize and publish noso wallet/node

on:
  workflow_dispatch:
    inputs:
      noso_tag:
        description: 'NosoWallet git tag'
        required: true

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build container image
      run: |
        echo "Recieved tag: ${{ github.event.inputs.noso_tag }}"
        make NOSO_VERSION=${{ github.event.inputs.noso_tag }} build
        
    - name: GHCR Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Push to GHCR
      run: make NOSO_VERSION=${{ github.event.inputs.noso_tag }} push
